### PR TITLE
Update setup.py

### PR DESCRIPTION
**Pull request by vrde**
It includes also external packages for hinting, generate documentation, etc. We are going to need it soon!

### CODE REVIEW

**Comment by rhsimplex** [comment]
Here's what I had to do to get it to work:

First, commented out numpy/scipy in `setup.py`:

``` python
    install_requires=[
#        'numpy>=1.10,<1.11',
#        'scipy>=0.17,<0.18',
        'scikit-image>=0.11,<0.12',
        'cairosvg>1,<2',
        'elasticsearch>=2.3,<2.4',
    ],
```

Then:

``` bash
sudo apt-get install libblas-dev liblapack-dev libatlas-base-dev gfortran
pip install numpy
pip install scipy
pip install -e .
```

**Comment by vrde** [comment]
Related? https://github.com/numpy/numpy/issues/2434

**Comment by vrde** [comment]
I've updated `setup.py` with a workaround, seems to work for me. Can you give it a try when you have time?

After that, we can push to Pypi.

**Comment by rhsimplex** [comment]
This still fails for me, though scipy seems to install ok...maybe scipy should be in setup requires as well?

``` bash
(env)ryan@ubuntu: image-match (add-setup-py) $ pip install .

```

``` text
...
Downloading/unpacking scikit-image>=0.11,<0.12 (from image-match==0.1.0)
  Downloading scikit-image-0.11.3.tar.gz (18.6MB): 18.6MB downloaded
  Running setup.py (path:/home/ryan/image-match/env/build/scikit-image/setup.py) egg_info for package scikit-image
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/home/ryan/image-match/env/build/scikit-image/setup.py", line 76, in <module>
        from numpy.distutils.core import setup
    ImportError: No module named numpy.distutils.core
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/home/ryan/image-match/env/build/scikit-image/setup.py", line 76, in <module>

    from numpy.distutils.core import setup

ImportError: No module named numpy.distutils.core

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /home/ryan/image-match/env/build/scikit-image
Traceback (most recent call last):
  File "/home/ryan/image-match/env/bin/pip", line 11, in <module>
    sys.exit(main())
  File "/home/ryan/image-match/env/local/lib/python2.7/site-packages/pip/__init__.py", line 185, in main
    return command.main(cmd_args)
  File "/home/ryan/image-match/env/local/lib/python2.7/site-packages/pip/basecommand.py", line 161, in main
    text = '\n'.join(complete_log)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 72: ordinal not in range(128)
```

Also, can we remove `requirements.txt` from this branch?

**Comment by vrde** [comment]
OK, I added some code to check if `numpy` is installed and, if not, to show to the user installing the lib some more info:

```
vrde@pulp:~/repos/image-match$ pip install --no-cache-dir .
You are using pip version 7.0.3, however version 8.1.0 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Processing /home/vrde/repos/image-match
    Complete output from command python setup.py egg_info:
    There is an issue installing numpy automatically as a dependency. Please install it manually using
     $ pip install numpy
    or try Anaconda: https://www.continuum.io/

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-zDAkkb-build
```

If `numpy` is found, this is what the user will see:

```
vrde@pulp:~/repos/image-match$ pip install --no-cache-dir .
You are using pip version 7.0.3, however version 8.1.0 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Processing /home/vrde/repos/image-match
Requirement already satisfied (use --upgrade to upgrade): numpy<1.11,>=1.10 in /home/vrde/.local/share/virtualenvs/ce9b5a9902946eb0/lib/python2.7/site-packages (from image-match==0.1.0)
Collecting scipy<0.18,>=0.17 (from image-match==0.1.0)
  Downloading scipy-0.17.0.tar.gz (12.4MB)
    100% |████████████████████████████████| 12.4MB 7.8MB/s 
Collecting scikit-image<0.13,>=0.12 (from image-match==0.1.0)
  Downloading scikit-image-0.12.3.tar.gz (20.7MB)
    100% |████████████████████████████████| 20.7MB 8.6MB/s 
Collecting cairosvg<2,>1 (from image-match==0.1.0)
  Downloading CairoSVG-1.0.20.tar.gz
Collecting elasticsearch<2.4,>=2.3 (from image-match==0.1.0)
  Downloading elasticsearch-2.3.0-py2.py3-none-any.whl (51kB)
    100% |████████████████████████████████| 53kB 1.3MB/s 
Collecting matplotlib>=1.3.1 (from scikit-image<0.13,>=0.12->image-match==0.1.0)
  Downloading matplotlib-1.5.1.tar.gz (54.0MB)
    100% |████████████████████████████████| 54.0MB 7.9MB/s 
...
```

**Pull request merged**
